# STAT 207 Lab Assignment 5 - Group Part


## <u>Case Study</u>: Exploring the Predictive Power of Explanatory Variables



### Coffee Dataset Information

In this individual assignment we will return to the `coffee.csv` dataset. Information about the variables in this dataset can be found here: https://corgis-edu.github.io/corgis/csv/coffee/

### Linear Regression Model

We intend to build linear regression models that will predict the `Flavor` of coffee brands *in this dataset* given the following explanatory variables.

* `Aroma`
* `Aftertaste`
* `Acidity`
* `Body`
* `Balance`
* `Uniformity`
* `Sweetness`
* `Moisture`
* `Color`
* `Species`


### Research Questions

In this group assignment we would like to answer the following questions about the coffee brands in the *entire dataset*.

1. Which explanatory variable in this list brings the most amount of predictive power to the model *by itself*?
2. Which explanatory variable in this list brings the second most amount of predictive power to the model *in addition to the variable that brings the most power*?
3. In the presence of ALL of the available explanatory variables, which explanatory variable brings the *least* amount of predictive power to the model?


<p>&nbsp;</p>
<table style="border: none;border-collapse: collapse;width:102pt;">
    <tbody>
        <tr>
            <td style="color:black;font-size:15px;font-weight:700;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:general;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;width:51pt;">Problem</td>
            <td style="color:black;font-size:15px;font-weight:700;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:general;vertical-align:bottom;border:.5pt solid windowtext;border-left:none;width:51pt;">Points</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">1.1</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">0.5</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">1.2</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">0.5</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">1.3</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">0.5</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">2.1</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">1</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">2.2</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">0.5</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">3.1</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">1</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">3.2</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">0.5</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">4.1</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">1</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;height:14.25pt;border-top:none;">4.2</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;border-top:none;border-left:none;">0.5</td>
        </tr>
        <tr>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:general;vertical-align:bottom;border:.5pt solid windowtext;background:#E7E6E6;height:14.25pt;border-top:none;">Total</td>
            <td style="color:black;font-size:15px;font-weight:400;font-style:normal;text-decoration:none;font-family:Calibri, sans-serif;text-align:right;vertical-align:bottom;border:.5pt solid windowtext;background:#E7E6E6;border-top:none;border-left:none;">6</td>
        </tr>
    </tbody>
</table>


In [9]:
import pandas as pd
import statsmodels.formula.api as smf
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

## 1. Coffee Dataset

### 1.1. Reading the csv

1. Read the `coffee.csv` into a dataframe. The strings that are used to represent missing values in this csv file are represented with 'nan'. Luckily, 'nan' is one of the string values that the **pd.read_csv()** function is automatically programmed to detect as a missing value and thus convert into a NaN type object.
2. Show the first 5 rows.
3. Show how many rows this dataframe has.

In [10]:
coffee_df = pd.read_csv("coffee.csv", na_values = ["nan"])
coffee_df.head()

Location_Country                Location_Region  Location_Altitude_Min  \
0    United States                           kona                      0   
1           Brazil  sul de minas - carmo de minas                     12   
2           Brazil  sul de minas - carmo de minas                     12   
3         Ethiopia                         sidamo                      0   
4         Ethiopia                         sidamo                      0   

   Location_Altitude_Max  Location_Altitude_Average  Year  \
0                      0                          0  2010   
1                     12                         12  2010   
2                     12                         12  2010   
3                      0                          0  2010   
4                      0                          0  2010   

                         Data_Owner Data_Type_Species Data_Type_Variety  \
0  kona pacific farmers cooperative           Arabica               NaN   
1          jacques pereira carneiro           Arabica    Yellow Bourbon   
2          jacques pereira carneiro           Arabica    Yellow Bourbon   
3       ethiopia commodity exchange           Arabica               NaN   
4       ethiopia commodity exchange           Arabica               NaN   

  Data_Type_Processing method  ...  Data_Scores_Flavor  \
0                         NaN  ...                8.42   
1                         NaN  ...                7.92   
2                         NaN  ...                7.92   
3                         NaN  ...                8.00   
4                         NaN  ...                7.83   

   Data_Scores_Aftertaste  Data_Scores_Acidity  Data_Scores_Body  \
0                    8.08                 7.75              7.67   
1                    7.92                 7.75              8.33   
2                    8.00                 7.75              7.92   
3                    7.83                 8.00              7.92   
4                    7.58                 8.00              7.83   

   Data_Scores_Balance  Data_Scores_Uniformity  Data_Scores_Sweetness  \
0                 7.83                    10.0                   10.0   
1                 8.00                    10.0                   10.0   
2                 8.00                    10.0                   10.0   
3                 7.83                    10.0                   10.0   
4                 7.50                    10.0                   10.0   

   Data_Scores_Moisture  Data_Scores_Total  Data_Color  
0                  0.00              86.25     Unknown  
1                  0.08              86.17     Unknown  
2                  0.01              86.17     Unknown  
3                  0.00              85.08     Unknown  
4                  0.10              83.83     Unknown  

[5 rows x 23 columns]

In [11]:
coffee_df.shape[0]

989

### 1.2. Dropping NaN Values

We only intend to use the `Aroma`, `Flavor`, `Aftertaste`, `Acidity`, `Body`, `Balance`, `Uniformity`, `Sweetness`, `Moisture`, `Color`, and `Species` variables in this dataframe.

1. Create a dataframe with just these variables.
2. Then drop all rows from this dataframe that have a NaN value.
3. How many rows did you drop?

In [12]:
coffee_df.dtypes

Location_Country                   object
Location_Region                    object
Location_Altitude_Min               int64
Location_Altitude_Max               int64
Location_Altitude_Average           int64
Year                                int64
Data_Owner                         object
Data_Type_Species                  object
Data_Type_Variety                  object
Data_Type_Processing method        object
Data_Production_Number of bags      int64
Data_Production_Bag weight        float64
Data_Scores_Aroma                 float64
Data_Scores_Flavor                float64
Data_Scores_Aftertaste            float64
Data_Scores_Acidity               float64
Data_Scores_Body                  float64
Data_Scores_Balance               float64
Data_Scores_Uniformity            float64
Data_Scores_Sweetness             float64
Data_Scores_Moisture              float64
Data_Scores_Total                 float64
Data_Color                         object
dtype: object

In [13]:
coffee_filtered = coffee_df[['Data_Scores_Aroma','Data_Scores_Flavor','Data_Scores_Aftertaste','Data_Scores_Acidity','Data_Scores_Body','Data_Scores_Balance','Data_Scores_Uniformity','Data_Scores_Sweetness','Data_Scores_Moisture','Data_Color','Data_Type_Species']]
coffee_filtered

Data_Scores_Aroma  Data_Scores_Flavor  Data_Scores_Aftertaste  \
0                 8.25                8.42                    8.08   
1                 8.17                7.92                    7.92   
2                 8.42                7.92                    8.00   
3                 7.67                8.00                    7.83   
4                 7.58                7.83                    7.58   
..                 ...                 ...                     ...   
984               7.58                7.67                    7.42   
985               0.00                0.00                    0.00   
986               8.00                7.75                    7.92   
987               7.67                7.75                    7.83   
988               7.50                7.42                    7.08   

     Data_Scores_Acidity  Data_Scores_Body  Data_Scores_Balance  \
0                   7.75              7.67                 7.83   
1                   7.75              8.33                 8.00   
2                   7.75              7.92                 8.00   
3                   8.00              7.92                 7.83   
4                   8.00              7.83                 7.50   
..                   ...               ...                  ...   
984                 7.42              7.67                 7.67   
985                 0.00              0.00                 0.00   
986                 8.00              7.92                 7.92   
987                 7.67              7.92                 7.83   
988                 7.42              7.50                 7.33   

     Data_Scores_Uniformity  Data_Scores_Sweetness  Data_Scores_Moisture  \
0                     10.00                  10.00                  0.00   
1                     10.00                  10.00                  0.08   
2                     10.00                  10.00                  0.01   
3                     10.00                  10.00                  0.00   
4                     10.00                  10.00                  0.10   
..                      ...                    ...                   ...   
984                    8.67                   8.67                  0.10   
985                    0.00                   0.00                  0.12   
986                   10.00                   8.00                  0.00   
987                   10.00                   7.92                  0.10   
988                   10.00                  10.00                  0.11   

       Data_Color Data_Type_Species  
0         Unknown           Arabica  
1         Unknown           Arabica  
2         Unknown           Arabica  
3         Unknown           Arabica  
4         Unknown           Arabica  
..            ...               ...  
984         Green           Arabica  
985         Green           Arabica  
986       Unknown           Robusta  
987  Bluish-Green           Robusta  
988    Blue-Green           Arabica  

[989 rows x 11 columns]

In [14]:
filtered_drop = coffee_filtered.dropna()
filtered_drop

Data_Scores_Aroma  Data_Scores_Flavor  Data_Scores_Aftertaste  \
0                 8.25                8.42                    8.08   
1                 8.17                7.92                    7.92   
2                 8.42                7.92                    8.00   
3                 7.67                8.00                    7.83   
4                 7.58                7.83                    7.58   
..                 ...                 ...                     ...   
984               7.58                7.67                    7.42   
985               0.00                0.00                    0.00   
986               8.00                7.75                    7.92   
987               7.67                7.75                    7.83   
988               7.50                7.42                    7.08   

     Data_Scores_Acidity  Data_Scores_Body  Data_Scores_Balance  \
0                   7.75              7.67                 7.83   
1                   7.75              8.33                 8.00   
2                   7.75              7.92                 8.00   
3                   8.00              7.92                 7.83   
4                   8.00              7.83                 7.50   
..                   ...               ...                  ...   
984                 7.42              7.67                 7.67   
985                 0.00              0.00                 0.00   
986                 8.00              7.92                 7.92   
987                 7.67              7.92                 7.83   
988                 7.42              7.50                 7.33   

     Data_Scores_Uniformity  Data_Scores_Sweetness  Data_Scores_Moisture  \
0                     10.00                  10.00                  0.00   
1                     10.00                  10.00                  0.08   
2                     10.00                  10.00                  0.01   
3                     10.00                  10.00                  0.00   
4                     10.00                  10.00                  0.10   
..                      ...                    ...                   ...   
984                    8.67                   8.67                  0.10   
985                    0.00                   0.00                  0.12   
986                   10.00                   8.00                  0.00   
987                   10.00                   7.92                  0.10   
988                   10.00                  10.00                  0.11   

       Data_Color Data_Type_Species  
0         Unknown           Arabica  
1         Unknown           Arabica  
2         Unknown           Arabica  
3         Unknown           Arabica  
4         Unknown           Arabica  
..            ...               ...  
984         Green           Arabica  
985         Green           Arabica  
986       Unknown           Robusta  
987  Bluish-Green           Robusta  
988    Blue-Green           Arabica  

[942 rows x 11 columns]

### 1.3. Dropping a Large Outlier

This dataset has a prominent outlier with an `Aroma` rating that is equal to 0. Drop this observation from the dataset.

In [15]:
aroma_row = filtered_drop.loc[filtered_drop['Data_Scores_Aroma'] == 0]
aroma_row

Data_Scores_Aroma  Data_Scores_Flavor  Data_Scores_Aftertaste  \
985                0.0                 0.0                     0.0   

     Data_Scores_Acidity  Data_Scores_Body  Data_Scores_Balance  \
985                  0.0               0.0                  0.0   

     Data_Scores_Uniformity  Data_Scores_Sweetness  Data_Scores_Moisture  \
985                     0.0                    0.0                  0.12   

    Data_Color Data_Type_Species  
985      Green           Arabica

In [16]:
filtered_drop = filtered_drop.drop(985)
filtered_drop

Data_Scores_Aroma  Data_Scores_Flavor  Data_Scores_Aftertaste  \
0                 8.25                8.42                    8.08   
1                 8.17                7.92                    7.92   
2                 8.42                7.92                    8.00   
3                 7.67                8.00                    7.83   
4                 7.58                7.83                    7.58   
..                 ...                 ...                     ...   
983               7.58                7.00                    6.75   
984               7.58                7.67                    7.42   
986               8.00                7.75                    7.92   
987               7.67                7.75                    7.83   
988               7.50                7.42                    7.08   

     Data_Scores_Acidity  Data_Scores_Body  Data_Scores_Balance  \
0                   7.75              7.67                 7.83   
1                   7.75              8.33                 8.00   
2                   7.75              7.92                 8.00   
3                   8.00              7.92                 7.83   
4                   8.00              7.83                 7.50   
..                   ...               ...                  ...   
983                 6.92              7.00                 6.92   
984                 7.42              7.67                 7.67   
986                 8.00              7.92                 7.92   
987                 7.67              7.92                 7.83   
988                 7.42              7.50                 7.33   

     Data_Scores_Uniformity  Data_Scores_Sweetness  Data_Scores_Moisture  \
0                     10.00                  10.00                  0.00   
1                     10.00                  10.00                  0.08   
2                     10.00                  10.00                  0.01   
3                     10.00                  10.00                  0.00   
4                     10.00                  10.00                  0.10   
..                      ...                    ...                   ...   
983                   10.00                  10.00                  0.11   
984                    8.67                   8.67                  0.10   
986                   10.00                   8.00                  0.00   
987                   10.00                   7.92                  0.10   
988                   10.00                  10.00                  0.11   

       Data_Color Data_Type_Species  
0         Unknown           Arabica  
1         Unknown           Arabica  
2         Unknown           Arabica  
3         Unknown           Arabica  
4         Unknown           Arabica  
..            ...               ...  
983         Green           Arabica  
984         Green           Arabica  
986       Unknown           Robusta  
987  Bluish-Green           Robusta  
988    Blue-Green           Arabica  

[941 rows x 11 columns]

## 2. <u>Research Question</u>: Most Independent Predictive Power

We would first like to answer the following research question using the *full dataset*.

`Which explanatory variable in this list brings the most amount of predictive power to the model by itself?`

### 2.1. 10 Candidate Models

Create 10 simple linear regression candidate models.

* One that predicts `Flavor` with `Aroma`
* One that predicts `Flavor` with `Aftertaste`
* One that predicts `Flavor` with `Acidity`
* One that predicts `Flavor` with`Body`
* One that predicts `Flavor` with `Balance`
* One that predicts `Flavor` with `Uniformity`
* One that predicts `Flavor` with `Sweetness`
* One that predicts `Flavor` with `Moisture`
* One that predicts `Flavor` with `Color`
* One that predicts `Flavor` with `Species`

Calculate/show the R^2 for each of these models.

In [17]:
#One that predicts Flavor with Aroma
lr_flavor_aroma = smf.ols(formula='Data_Scores_Flavor~Data_Scores_Aroma',data=filtered_drop).fit()
lr_flavor_aroma.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.536
Model:                            OLS   Adj. R-squared:                  0.536
Method:                 Least Squares   F-statistic:                     1087.
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          5.97e-159
Time:                        16:55:07   Log-Likelihood:                 35.142
No. Observations:                 941   AIC:                            -66.28
Df Residuals:                     939   BIC:                            -56.59
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
=====================================================================================
                        coef    std err          t      P>|t|      [0.025      0.975]
-------------------------------------------------------------------------------------
Intercept             1.4883      0.183      8.112      0.000       1.128       1.848
Data_Scores_Aroma     0.7963      0.024     32.966      0.000       0.749       0.844
==============================================================================
Omnibus:                      208.338   Durbin-Watson:                   1.524
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3789.962
Skew:                           0.490   Prob(JB):                         0.00
Kurtosis:                      12.783   Cond. No.                         186.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [18]:
#One that predicts Flavor with Aftertaste
lr_flavor_aftertaste = smf.ols(formula='Data_Scores_Flavor~Data_Scores_Aftertaste',data=filtered_drop).fit()
lr_flavor_aftertaste.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.755
Model:                            OLS   Adj. R-squared:                  0.754
Method:                 Least Squares   F-statistic:                     2886.
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          1.20e-288
Time:                        16:55:18   Log-Likelihood:                 334.25
No. Observations:                 941   AIC:                            -664.5
Df Residuals:                     939   BIC:                            -654.8
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                  1.1979      0.118     10.150      0.000       0.966       1.429
Data_Scores_Aftertaste     0.8552      0.016     53.725      0.000       0.824       0.886
==============================================================================
Omnibus:                       16.081   Durbin-Watson:                   1.782
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               28.895
Skew:                          -0.004   Prob(JB):                     5.32e-07
Kurtosis:                       3.858   Cond. No.                         161.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [19]:
#One that predicts Flavor with Acidity
lr_flavor_acidity = smf.ols(formula='Data_Scores_Flavor~Data_Scores_Acidity',data=filtered_drop).fit()
lr_flavor_acidity.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.594
Model:                            OLS   Adj. R-squared:                  0.593
Method:                 Least Squares   F-statistic:                     1371.
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          9.12e-186
Time:                        16:55:28   Log-Likelihood:                 96.970
No. Observations:                 941   AIC:                            -189.9
Df Residuals:                     939   BIC:                            -180.2
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept               1.1418      0.173      6.611      0.000       0.803       1.481
Data_Scores_Acidity     0.8454      0.023     37.030      0.000       0.801       0.890
==============================================================================
Omnibus:                      173.514   Durbin-Watson:                   1.613
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3281.324
Skew:                           0.203   Prob(JB):                         0.00
Kurtosis:                      12.139   Cond. No.                         187.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [20]:
#One that predicts Flavor with Body
lr_flavor_body = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Body",data=filtered_drop).fit()
lr_flavor_body.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.391
Model:                            OLS   Adj. R-squared:                  0.390
Method:                 Least Squares   F-statistic:                     602.3
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          3.74e-103
Time:                        16:55:36   Log-Likelihood:                -93.451
No. Observations:                 941   AIC:                             190.9
Df Residuals:                     939   BIC:                             200.6
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
====================================================================================
                       coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------
Intercept            2.2889      0.214     10.706      0.000       1.869       2.708
Data_Scores_Body     0.6972      0.028     24.542      0.000       0.641       0.753
==============================================================================
Omnibus:                      177.144   Durbin-Watson:                   1.251
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2303.617
Skew:                           0.436   Prob(JB):                         0.00
Kurtosis:                      10.615   Cond. No.                         188.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [21]:
#One that predicts Flavor with Balance
lr_flavor_balance = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Balance",data=filtered_drop).fit()
lr_flavor_balance.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.554
Model:                            OLS   Adj. R-squared:                  0.553
Method:                 Least Squares   F-statistic:                     1164.
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          1.33e-166
Time:                        16:55:42   Log-Likelihood:                 52.781
No. Observations:                 941   AIC:                            -101.6
Df Residuals:                     939   BIC:                            -91.87
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
=======================================================================================
                          coef    std err          t      P>|t|      [0.025      0.975]
---------------------------------------------------------------------------------------
Intercept               1.9758      0.163     12.121      0.000       1.656       2.296
Data_Scores_Balance     0.7390      0.022     34.119      0.000       0.697       0.782
==============================================================================
Omnibus:                      139.410   Durbin-Watson:                   1.592
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             1668.009
Skew:                          -0.175   Prob(JB):                         0.00
Kurtosis:                       9.513   Cond. No.                         167.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [22]:
#One that predicts Flavor with Uniformity
lr_flavor_uniformity = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Uniformity",data=filtered_drop).fit()
lr_flavor_uniformity.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.057
Model:                            OLS   Adj. R-squared:                  0.056
Method:                 Least Squares   F-statistic:                     57.01
Date:                Sat, 23 Sep 2023   Prob (F-statistic):           1.03e-13
Time:                        16:55:54   Log-Likelihood:                -298.88
No. Observations:                 941   AIC:                             601.8
Df Residuals:                     939   BIC:                             611.5
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                  5.9265      0.213     27.846      0.000       5.509       6.344
Data_Scores_Uniformity     0.1631      0.022      7.550      0.000       0.121       0.206
==============================================================================
Omnibus:                       42.775   Durbin-Watson:                   0.862
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              124.144
Skew:                          -0.112   Prob(JB):                     1.10e-27
Kurtosis:                       4.765   Cond. No.                         195.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [23]:
#One that predicts Flavor with Sweetness
lr_flavor_sweetness = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Sweetness",data=filtered_drop).fit()
lr_flavor_sweetness.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.015
Model:                            OLS   Adj. R-squared:                  0.014
Method:                 Least Squares   F-statistic:                     14.75
Date:                Sat, 23 Sep 2023   Prob (F-statistic):           0.000131
Time:                        16:56:01   Log-Likelihood:                -319.28
No. Observations:                 941   AIC:                             642.6
Df Residuals:                     939   BIC:                             652.3
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
Intercept                 6.8477      0.178     38.393      0.000       6.498       7.198
Data_Scores_Sweetness     0.0695      0.018      3.841      0.000       0.034       0.105
==============================================================================
Omnibus:                       49.326   Durbin-Watson:                   0.643
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              124.175
Skew:                          -0.257   Prob(JB):                     1.09e-27
Kurtosis:                       4.704   Cond. No.                         160.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [24]:
#One that predicts Flavor with Moisture
lr_flavor_moisture = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Moisture",data=filtered_drop).fit()
lr_flavor_moisture.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.020
Model:                            OLS   Adj. R-squared:                  0.019
Method:                 Least Squares   F-statistic:                     19.07
Date:                Sat, 23 Sep 2023   Prob (F-statistic):           1.40e-05
Time:                        16:56:05   Log-Likelihood:                -317.15
No. Observations:                 941   AIC:                             638.3
Df Residuals:                     939   BIC:                             648.0
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
========================================================================================
                           coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------
Intercept                7.6324      0.026    297.646      0.000       7.582       7.683
Data_Scores_Moisture    -1.0882      0.249     -4.367      0.000      -1.577      -0.599
==============================================================================
Omnibus:                       56.945   Durbin-Watson:                   0.646
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              152.994
Skew:                          -0.290   Prob(JB):                     6.00e-34
Kurtosis:                       4.888   Cond. No.                         22.7
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [25]:
#One that predicts Flavor with Color
lr_flavor_color = smf.ols(formula="Data_Scores_Flavor~Data_Color",data=filtered_drop).fit()
lr_flavor_color.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.016
Model:                            OLS   Adj. R-squared:                  0.013
Method:                 Least Squares   F-statistic:                     4.969
Date:                Sat, 23 Sep 2023   Prob (F-statistic):            0.00200
Time:                        16:56:11   Log-Likelihood:                -319.19
No. Observations:                 941   AIC:                             646.4
Df Residuals:                     937   BIC:                             665.8
Df Model:                           3                                         
Covariance Type:            nonrobust                                         
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                      7.6064      0.045    170.174      0.000       7.519       7.694
Data_Color[T.Bluish-Green]     0.0017      0.057      0.031      0.975      -0.109       0.113
Data_Color[T.Green]           -0.1014      0.047     -2.177      0.030      -0.193      -0.010
Data_Color[T.Unknown]         -0.0168      0.056     -0.302      0.763      -0.126       0.092
==============================================================================
Omnibus:                       60.759   Durbin-Watson:                   0.642
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              155.386
Skew:                          -0.336   Prob(JB):                     1.81e-34
Kurtosis:                       4.874   Cond. No.                         10.6
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [26]:
#One that predicts Flavor with Species
lr_flavor_species = smf.ols(formula="Data_Scores_Flavor~Data_Type_Species",data=filtered_drop).fit()
lr_flavor_species.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.005
Model:                            OLS   Adj. R-squared:                  0.004
Method:                 Least Squares   F-statistic:                     4.326
Date:                Sat, 23 Sep 2023   Prob (F-statistic):             0.0378
Time:                        16:56:17   Log-Likelihood:                -324.45
No. Observations:                 941   AIC:                             652.9
Df Residuals:                     939   BIC:                             662.6
Df Model:                           1                                         
Covariance Type:            nonrobust                                         
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                        7.5274      0.011    665.507      0.000       7.505       7.550
Data_Type_Species[T.Robusta]     0.1389      0.067      2.080      0.038       0.008       0.270
==============================================================================
Omnibus:                       60.337   Durbin-Watson:                   0.608
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              163.211
Skew:                          -0.312   Prob(JB):                     3.62e-36
Kurtosis:                       4.942   Cond. No.                         6.00
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

### 2.2. Answer

Use your analyses from 2.1 to answer the research question.

Aftertaste had the highest r^2 value of 0.755 which means aftertaste has the highest predictive power on Flavor.

## 3. Most Additional Predictive Power

We would next like to answer the following research question using the *full dataset*.


`Which explanatory variable in this list brings the second most amount of predictive power to the model in addition to the variable that brings the most power`?

### 3.1. 9 Candidate Models

Create 9 linear regression candidate models.

* One that predicts `Flavor` with `Aroma` and the `variable you selected in 2.1`
* ...
* One that predicts `Flavor` with `Color` and the `variable you selected in 2.1`
* One that predicts `Flavor` with `Species` and the `variable you selected in 2.1`

*(Or in other words each candidate model should include the explanatory variable that you selected in 2.1 and one other available explanatory variable in the list).*

Calculate/show the R^2 for each of these models.

In [28]:
#One that predicts Flavor with Aroma and Aftertaste
lr_flavor_aroma_aftertaste = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Aroma+Data_Scores_Aftertaste",data=filtered_drop).fit()
lr_flavor_aroma_aftertaste.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.787
Model:                            OLS   Adj. R-squared:                  0.787
Method:                 Least Squares   F-statistic:                     1733.
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          1.01e-315
Time:                        16:57:55   Log-Likelihood:                 401.01
No. Observations:                 941   AIC:                            -796.0
Df Residuals:                     938   BIC:                            -781.5
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                  0.3992      0.129      3.102      0.002       0.147       0.652
Data_Scores_Aroma          0.2720      0.023     11.959      0.000       0.227       0.317
Data_Scores_Aftertaste     0.6843      0.021     33.217      0.000       0.644       0.725
==============================================================================
Omnibus:                       24.999   Durbin-Watson:                   1.835
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               53.453
Skew:                          -0.069   Prob(JB):                     2.47e-12
Kurtosis:                       4.159   Cond. No.                         267.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [29]:
#One that predicts Flavor with Acidity and Aftertaste
lr_flavor_acidity_aftertaste = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Acidity+Data_Scores_Aftertaste",data=filtered_drop).fit()
lr_flavor_acidity_aftertaste.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.794
Model:                            OLS   Adj. R-squared:                  0.794
Method:                 Least Squares   F-statistic:                     1810.
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          1.04e-322
Time:                        16:58:05   Log-Likelihood:                 417.14
No. Observations:                 941   AIC:                            -828.3
Df Residuals:                     938   BIC:                            -813.7
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                  0.3325      0.126      2.642      0.008       0.086       0.579
Data_Scores_Acidity        0.3199      0.024     13.443      0.000       0.273       0.367
Data_Scores_Aftertaste     0.6456      0.021     30.239      0.000       0.604       0.687
==============================================================================
Omnibus:                       51.183   Durbin-Watson:                   1.852
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              181.227
Skew:                           0.047   Prob(JB):                     4.44e-40
Kurtosis:                       5.148   Cond. No.                         265.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [30]:
#One that predicts Flavor with Body and Aftertaste
lr_flavor_body_aftertaste = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Body+Data_Scores_Aftertaste",data=filtered_drop).fit()
lr_flavor_body_aftertaste.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.763
Model:                            OLS   Adj. R-squared:                  0.762
Method:                 Least Squares   F-statistic:                     1507.
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          1.03e-293
Time:                        16:58:11   Log-Likelihood:                 350.17
No. Observations:                 941   AIC:                            -694.3
Df Residuals:                     938   BIC:                            -679.8
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                  0.7602      0.139      5.456      0.000       0.487       1.034
Data_Scores_Body           0.1311      0.023      5.683      0.000       0.086       0.176
Data_Scores_Aftertaste     0.7811      0.020     38.343      0.000       0.741       0.821
==============================================================================
Omnibus:                       16.982   Durbin-Watson:                   1.804
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               31.115
Skew:                          -0.020   Prob(JB):                     1.75e-07
Kurtosis:                       3.890   Cond. No.                         273.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [31]:
#One that predicts Flavor with Balance and Aftertaste
lr_flavor_balance_aftertaste = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Balance+Data_Scores_Aftertaste",data=filtered_drop).fit()
lr_flavor_balance_aftertaste.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.766
Model:                            OLS   Adj. R-squared:                  0.765
Method:                 Least Squares   F-statistic:                     1532.
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          3.26e-296
Time:                        16:58:18   Log-Likelihood:                 355.95
No. Observations:                 941   AIC:                            -705.9
Df Residuals:                     938   BIC:                            -691.4
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                  0.8992      0.124      7.263      0.000       0.656       1.142
Data_Scores_Balance        0.1672      0.025      6.654      0.000       0.118       0.217
Data_Scores_Aftertaste     0.7257      0.025     29.132      0.000       0.677       0.775
==============================================================================
Omnibus:                       17.245   Durbin-Watson:                   1.799
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               30.271
Skew:                          -0.080   Prob(JB):                     2.67e-07
Kurtosis:                       3.864   Cond. No.                         244.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [32]:
#One that predicts Flavor with Uniformity and Aftertaste
lr_flavor_uniformity_aftertaste = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Uniformity+Data_Scores_Aftertaste",data=filtered_drop).fit()
lr_flavor_uniformity_aftertaste.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.756
Model:                            OLS   Adj. R-squared:                  0.755
Method:                 Least Squares   F-statistic:                     1453.
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          5.07e-288
Time:                        16:58:25   Log-Likelihood:                 337.03
No. Observations:                 941   AIC:                            -668.1
Df Residuals:                     938   BIC:                            -653.5
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                  1.0020      0.144      6.953      0.000       0.719       1.285
Data_Scores_Uniformity     0.0267      0.011      2.357      0.019       0.004       0.049
Data_Scores_Aftertaste     0.8462      0.016     51.826      0.000       0.814       0.878
==============================================================================
Omnibus:                       15.494   Durbin-Watson:                   1.794
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               27.423
Skew:                          -0.001   Prob(JB):                     1.11e-06
Kurtosis:                       3.836   Cond. No.                         324.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [33]:
#One that predicts Flavor with Sweetness and Aftertaste
lr_flavor_sweetness_aftertaste = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Sweetness+Data_Scores_Aftertaste",data=filtered_drop).fit()
lr_flavor_sweetness_aftertaste.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.757
Model:                            OLS   Adj. R-squared:                  0.756
Method:                 Least Squares   F-statistic:                     1460.
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          1.01e-288
Time:                        16:58:34   Log-Likelihood:                 338.64
No. Observations:                 941   AIC:                            -671.3
Df Residuals:                     938   BIC:                            -656.7
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                  0.9651      0.141      6.830      0.000       0.688       1.242
Data_Scores_Sweetness      0.0268      0.009      2.967      0.003       0.009       0.045
Data_Scores_Aftertaste     0.8510      0.016     53.474      0.000       0.820       0.882
==============================================================================
Omnibus:                       14.584   Durbin-Watson:                   1.786
Prob(Omnibus):                  0.001   Jarque-Bera (JB):               25.175
Skew:                          -0.010   Prob(JB):                     3.41e-06
Kurtosis:                       3.801   Cond. No.                         318.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [34]:
#One that predicts Flavor with Moisture and Aftertaste
lr_flavor_moisture_aftertaste = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Moisture+Data_Scores_Aftertaste",data=filtered_drop).fit()
lr_flavor_moisture_aftertaste.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.755
Model:                            OLS   Adj. R-squared:                  0.755
Method:                 Least Squares   F-statistic:                     1447.
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          2.37e-287
Time:                        16:58:41   Log-Likelihood:                 335.48
No. Observations:                 941   AIC:                            -665.0
Df Residuals:                     938   BIC:                            -650.4
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
==========================================================================================
                             coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                  1.1435      0.123      9.302      0.000       0.902       1.385
Data_Scores_Moisture       0.1990      0.127      1.567      0.117      -0.050       0.448
Data_Scores_Aftertaste     0.8600      0.016     53.076      0.000       0.828       0.892
==============================================================================
Omnibus:                       16.057   Durbin-Watson:                   1.785
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               28.834
Skew:                           0.004   Prob(JB):                     5.48e-07
Kurtosis:                       3.858   Cond. No.                         192.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [35]:
#One that predicts Flavor with Color and Aftertaste
lr_flavor_species_aftertaste = smf.ols(formula="Data_Scores_Flavor~Data_Color+Data_Scores_Aftertaste",data=filtered_drop).fit()
lr_flavor_species_aftertaste.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.756
Model:                            OLS   Adj. R-squared:                  0.755
Method:                 Least Squares   F-statistic:                     724.8
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          8.00e-285
Time:                        16:58:49   Log-Likelihood:                 336.94
No. Observations:                 941   AIC:                            -663.9
Df Residuals:                     936   BIC:                            -639.6
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                      1.1725      0.123      9.549      0.000       0.931       1.413
Data_Color[T.Bluish-Green]    -0.0487      0.028     -1.726      0.085      -0.104       0.007
Data_Color[T.Green]           -0.0066      0.023     -0.285      0.776      -0.052       0.039
Data_Color[T.Unknown]         -0.0143      0.028     -0.519      0.604      -0.069       0.040
Data_Scores_Aftertaste         0.8602      0.016     53.282      0.000       0.828       0.892
==============================================================================
Omnibus:                       16.118   Durbin-Watson:                   1.793
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               28.943
Skew:                           0.014   Prob(JB):                     5.19e-07
Kurtosis:                       3.859   Cond. No.                         169.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [36]:
#One that predicts Flavor with Species and Aftertaste
lr_flavor_species_aftertaste = smf.ols(formula="Data_Scores_Flavor~Data_Type_Species+Data_Scores_Aftertaste",data=filtered_drop).fit()
lr_flavor_species_aftertaste.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.755
Model:                            OLS   Adj. R-squared:                  0.754
Method:                 Least Squares   F-statistic:                     1443.
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          5.22e-287
Time:                        16:58:56   Log-Likelihood:                 334.69
No. Observations:                 941   AIC:                            -663.4
Df Residuals:                     938   BIC:                            -648.8
Df Model:                           2                                         
Covariance Type:            nonrobust                                         
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                        1.1882      0.118     10.029      0.000       0.956       1.421
Data_Type_Species[T.Robusta]    -0.0312      0.033     -0.935      0.350      -0.097       0.034
Data_Scores_Aftertaste           0.8566      0.016     53.566      0.000       0.825       0.888
==============================================================================
Omnibus:                       16.348   Durbin-Watson:                   1.785
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               29.547
Skew:                          -0.011   Prob(JB):                     3.84e-07
Kurtosis:                       3.868   Cond. No.                         162.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

### 3.2. Answer

Use your analyses from 3.1 to answer the research question.

Acidity with aftertaste had the highest r^2 value of 0.794 which means acidity with aftertaste has the highest predictive power on Flavor.

## 4. Least Amount of Predictive Power (Considering All other Variables)

Finally, we'd like to answer the following research question using the *full dataset*.

`In the presence of ALL of the available explanatory variables, which explanatory variable brings the *least* amount of predictive power to the model?`

### 4.1. 10 Candidate Models

Create 10 candidate models.

* One that predicts `Flavor` with all explanatory variables except for `Aroma`
* One that predicts `Flavor` with all explanatory variables except for `Aftertaste`
* One that predicts `Flavor` with all explanatory variables except for `Acidity`
* One that predicts `Flavor` with all explanatory variables except for`Body`
* One that predicts `Flavor` with all explanatory variables except for `Balance`
* One that predicts `Flavor` with all explanatory variables except for `Uniformity`
* One that predicts `Flavor` with all explanatory variables except for `Sweetness`
* One that predicts `Flavor` with all explanatory variables except for `Moisture`
* One that predicts `Flavor` with all explanatory variables except for `Color`
* One that predicts `Flavor` with all explanatory variables except for `Species`

Calculate the R^2 for each of these models.

In [ ]:
#lr_flavor_except_aroma = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Aroma+Data_Scores_Aftertaste+Data_Scores_Acidity+Data_Scores_Body+Data_Scores_Balance+Data_Scores_Uniformity+Data_Scores_Sweetness+Data_Scores_Moisture+Data_Color+Data_Type_Species",data=coffee_df).fit()

In [37]:
#One that predicts Flavor with all explanatory variables except for Aroma (should be 10)
lr_flavor_except_aroma = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Aftertaste+Data_Scores_Acidity+Data_Scores_Body+Data_Scores_Balance+Data_Scores_Uniformity+Data_Scores_Sweetness+Data_Scores_Moisture+Data_Color+Data_Type_Species",data=filtered_drop).fit()
lr_flavor_except_aroma.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.803
Model:                            OLS   Adj. R-squared:                  0.801
Method:                 Least Squares   F-statistic:                     344.2
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          1.44e-318
Time:                        17:01:04   Log-Likelihood:                 437.71
No. Observations:                 941   AIC:                            -851.4
Df Residuals:                     929   BIC:                            -793.3
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                       -0.2320      0.169     -1.369      0.171      -0.565       0.101
Data_Color[T.Bluish-Green]      -0.0435      0.026     -1.692      0.091      -0.094       0.007
Data_Color[T.Green]             -0.0097      0.021     -0.455      0.649      -0.051       0.032
Data_Color[T.Unknown]           -0.0129      0.025     -0.507      0.612      -0.063       0.037
Data_Type_Species[T.Robusta]     0.0341      0.040      0.857      0.391      -0.044       0.112
Data_Scores_Aftertaste           0.5683      0.027     21.223      0.000       0.516       0.621
Data_Scores_Acidity              0.2858      0.024     11.807      0.000       0.238       0.333
Data_Scores_Body                 0.0560      0.023      2.411      0.016       0.010       0.102
Data_Scores_Balance              0.0859      0.025      3.391      0.001       0.036       0.136
Data_Scores_Uniformity           0.0106      0.011      0.920      0.358      -0.012       0.033
Data_Scores_Sweetness            0.0225      0.012      1.954      0.051   -9.68e-05       0.045
Data_Scores_Moisture             0.1428      0.121      1.177      0.240      -0.095       0.381
==============================================================================
Omnibus:                       46.438   Durbin-Watson:                   1.880
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              153.416
Skew:                           0.009   Prob(JB):                     4.85e-34
Kurtosis:                       4.978   Cond. No.                         703.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [38]:
#One that predicts Flavor with all explanatory variables except for Aftertaste
lr_flavor_except_aftertaste = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Aroma+Data_Scores_Acidity+Data_Scores_Body+Data_Scores_Balance+Data_Scores_Uniformity+Data_Scores_Sweetness+Data_Scores_Moisture+Data_Color+Data_Type_Species",data=filtered_drop).fit()
lr_flavor_except_aftertaste.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.753
Model:                            OLS   Adj. R-squared:                  0.750
Method:                 Least Squares   F-statistic:                     256.9
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          1.02e-272
Time:                        17:01:15   Log-Likelihood:                 330.48
No. Observations:                 941   AIC:                            -637.0
Df Residuals:                     929   BIC:                            -578.8
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                       -1.0495      0.196     -5.356      0.000      -1.434      -0.665
Data_Color[T.Bluish-Green]      -0.0144      0.029     -0.497      0.620      -0.071       0.042
Data_Color[T.Green]             -0.0077      0.024     -0.322      0.747      -0.054       0.039
Data_Color[T.Unknown]           -0.0027      0.029     -0.093      0.926      -0.059       0.053
Data_Type_Species[T.Robusta]     0.1001      0.044      2.255      0.024       0.013       0.187
Data_Scores_Aroma                0.3214      0.025     13.011      0.000       0.273       0.370
Data_Scores_Acidity              0.3977      0.026     15.367      0.000       0.347       0.448
Data_Scores_Body                 0.1076      0.026      4.174      0.000       0.057       0.158
Data_Scores_Balance              0.2354      0.026      8.945      0.000       0.184       0.287
Data_Scores_Uniformity           0.0207      0.013      1.609      0.108      -0.005       0.046
Data_Scores_Sweetness            0.0370      0.013      2.862      0.004       0.012       0.062
Data_Scores_Moisture            -0.0676      0.136     -0.499      0.618      -0.334       0.198
==============================================================================
Omnibus:                      124.327   Durbin-Watson:                   1.855
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              914.097
Skew:                          -0.337   Prob(JB):                    3.21e-199
Kurtosis:                       7.781   Cond. No.                         727.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [39]:
#One that predicts Flavor with all explanatory variables except for Acidity
lr_flavor_except_acidity = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Aroma+Data_Scores_Aftertaste+Data_Scores_Body+Data_Scores_Balance+Data_Scores_Uniformity+Data_Scores_Sweetness+Data_Scores_Moisture+Data_Color+Data_Type_Species",data=filtered_drop).fit()
lr_flavor_except_acidity.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.798
Model:                            OLS   Adj. R-squared:                  0.796
Method:                 Least Squares   F-statistic:                     334.3
Date:                Sat, 23 Sep 2023   Prob (F-statistic):          7.11e-314
Time:                        17:01:30   Log-Likelihood:                 426.74
No. Observations:                 941   AIC:                            -829.5
Df Residuals:                     929   BIC:                            -771.3
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                       -0.2897      0.174     -1.662      0.097      -0.632       0.052
Data_Color[T.Bluish-Green]      -0.0455      0.026     -1.749      0.081      -0.097       0.006
Data_Color[T.Green]             -0.0064      0.022     -0.299      0.765      -0.049       0.036
Data_Color[T.Unknown]           -0.0057      0.026     -0.223      0.823      -0.056       0.045
Data_Type_Species[T.Robusta]     0.0461      0.040      1.146      0.252      -0.033       0.125
Data_Scores_Aroma                0.2454      0.023     10.713      0.000       0.200       0.290
Data_Scores_Aftertaste           0.5939      0.027     22.375      0.000       0.542       0.646
Data_Scores_Body                 0.0755      0.023      3.236      0.001       0.030       0.121
Data_Scores_Balance              0.0811      0.026      3.148      0.002       0.031       0.132
Data_Scores_Uniformity           0.0086      0.012      0.740      0.460      -0.014       0.031
Data_Scores_Sweetness            0.0298      0.012      2.547      0.011       0.007       0.053
Data_Scores_Moisture             0.1557      0.123      1.268      0.205      -0.085       0.397
==============================================================================
Omnibus:                       22.014   Durbin-Watson:                   1.863
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               42.100
Skew:                          -0.104   Prob(JB):                     7.21e-10
Kurtosis:                       4.015   Cond. No.                         715.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [42]:
#One that predicts Flavor with all explanatory variables except forBody
lr_flavor_except_body = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Aroma+Data_Scores_Aftertaste+Data_Scores_Acidity+Data_Scores_Balance+Data_Scores_Uniformity+Data_Scores_Sweetness+Data_Scores_Moisture+Data_Color+Data_Type_Species",data=filtered_drop).fit()
lr_flavor_except_body.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.819
Model:                            OLS   Adj. R-squared:                  0.817
Method:                 Least Squares   F-statistic:                     382.1
Date:                Sat, 23 Sep 2023   Prob (F-statistic):               0.00
Time:                        17:02:52   Log-Likelihood:                 477.56
No. Observations:                 941   AIC:                            -931.1
Df Residuals:                     929   BIC:                            -873.0
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                       -0.5587      0.160     -3.485      0.001      -0.873      -0.244
Data_Color[T.Bluish-Green]      -0.0233      0.025     -0.949      0.343      -0.072       0.025
Data_Color[T.Green]              0.0077      0.020      0.381      0.703      -0.032       0.047
Data_Color[T.Unknown]            0.0065      0.024      0.269      0.788      -0.041       0.054
Data_Type_Species[T.Robusta]     0.0327      0.038      0.858      0.391      -0.042       0.107
Data_Scores_Aroma                0.2070      0.022      9.404      0.000       0.164       0.250
Data_Scores_Aftertaste           0.5053      0.026     19.098      0.000       0.453       0.557
Data_Scores_Acidity              0.2532      0.023     10.846      0.000       0.207       0.299
Data_Scores_Balance              0.0689      0.023      2.965      0.003       0.023       0.115
Data_Scores_Uniformity           0.0058      0.011      0.529      0.597      -0.016       0.027
Data_Scores_Sweetness            0.0275      0.011      2.481      0.013       0.006       0.049
Data_Scores_Moisture             0.1362      0.116      1.171      0.242      -0.092       0.364
==============================================================================
Omnibus:                       43.661   Durbin-Watson:                   1.899
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              132.053
Skew:                          -0.088   Prob(JB):                     2.11e-29
Kurtosis:                       4.827   Cond. No.                         695.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [41]:
#One that predicts Flavor with all explanatory variables except for Balance
lr_flavor_except_balance = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Aroma+Data_Scores_Aftertaste+Data_Scores_Acidity+Data_Scores_Body+Data_Scores_Uniformity+Data_Scores_Sweetness+Data_Scores_Moisture+Data_Color+Data_Type_Species",data=filtered_drop).fit()
lr_flavor_except_balance.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.819
Model:                            OLS   Adj. R-squared:                  0.817
Method:                 Least Squares   F-statistic:                     381.5
Date:                Sat, 23 Sep 2023   Prob (F-statistic):               0.00
Time:                        17:02:25   Log-Likelihood:                 476.99
No. Observations:                 941   AIC:                            -930.0
Df Residuals:                     929   BIC:                            -871.8
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                       -0.6758      0.169     -4.002      0.000      -1.007      -0.344
Data_Color[T.Bluish-Green]      -0.0276      0.025     -1.117      0.264      -0.076       0.021
Data_Color[T.Green]              0.0019      0.020      0.091      0.928      -0.038       0.042
Data_Color[T.Unknown]           -0.0015      0.024     -0.060      0.952      -0.049       0.046
Data_Type_Species[T.Robusta]     0.0344      0.038      0.900      0.368      -0.041       0.109
Data_Scores_Aroma                0.2111      0.022      9.664      0.000       0.168       0.254
Data_Scores_Aftertaste           0.5207      0.025     21.181      0.000       0.472       0.569
Data_Scores_Acidity              0.2524      0.023     10.758      0.000       0.206       0.298
Data_Scores_Body                 0.0586      0.021      2.767      0.006       0.017       0.100
Data_Scores_Uniformity           0.0106      0.011      0.963      0.336      -0.011       0.032
Data_Scores_Sweetness            0.0292      0.011      2.637      0.009       0.007       0.051
Data_Scores_Moisture             0.1103      0.116      0.949      0.343      -0.118       0.338
==============================================================================
Omnibus:                       42.484   Durbin-Watson:                   1.910
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              125.549
Skew:                          -0.090   Prob(JB):                     5.46e-28
Kurtosis:                       4.780   Cond. No.                         730.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [43]:
#One that predicts Flavor with all explanatory variables except for Uniformity
lr_flavor_except_uniformity = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Aroma+Data_Scores_Aftertaste+Data_Scores_Acidity+Data_Scores_Body+Data_Scores_Balance+Data_Scores_Sweetness+Data_Scores_Moisture+Data_Color+Data_Type_Species",data=filtered_drop).fit()
lr_flavor_except_uniformity.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.820
Model:                            OLS   Adj. R-squared:                  0.817
Method:                 Least Squares   F-statistic:                     383.7
Date:                Sat, 23 Sep 2023   Prob (F-statistic):               0.00
Time:                        17:03:20   Log-Likelihood:                 479.17
No. Observations:                 941   AIC:                            -934.3
Df Residuals:                     929   BIC:                            -876.2
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                       -0.6296      0.163     -3.861      0.000      -0.950      -0.310
Data_Color[T.Bluish-Green]      -0.0291      0.025     -1.178      0.239      -0.078       0.019
Data_Color[T.Green]              0.0026      0.020      0.128      0.898      -0.037       0.043
Data_Color[T.Unknown]            0.0002      0.024      0.007      0.995      -0.048       0.048
Data_Type_Species[T.Robusta]     0.0440      0.036      1.205      0.229      -0.028       0.116
Data_Scores_Aroma                0.2047      0.022      9.300      0.000       0.161       0.248
Data_Scores_Aftertaste           0.4985      0.027     18.677      0.000       0.446       0.551
Data_Scores_Acidity              0.2470      0.024     10.494      0.000       0.201       0.293
Data_Scores_Body                 0.0412      0.022      1.859      0.063      -0.002       0.085
Data_Scores_Balance              0.0558      0.024      2.289      0.022       0.008       0.104
Data_Scores_Sweetness            0.0313      0.010      3.126      0.002       0.012       0.051
Data_Scores_Moisture             0.1317      0.116      1.135      0.257      -0.096       0.359
==============================================================================
Omnibus:                       43.824   Durbin-Watson:                   1.899
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              129.734
Skew:                          -0.111   Prob(JB):                     6.74e-29
Kurtosis:                       4.805   Cond. No.                         674.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [50]:
lr_flavor_except_uniformity.rsquared

0.8196034397074634

In [44]:
#One that predicts Flavor with all explanatory variables except for Sweetness
lr_flavor_except_sweetness = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Aroma+Data_Scores_Aftertaste+Data_Scores_Acidity+Data_Scores_Body+Data_Scores_Balance+Data_Scores_Uniformity+Data_Scores_Moisture+Data_Color+Data_Type_Species",data=filtered_drop).fit()
lr_flavor_except_sweetness.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.818
Model:                            OLS   Adj. R-squared:                  0.816
Method:                 Least Squares   F-statistic:                     380.8
Date:                Sat, 23 Sep 2023   Prob (F-statistic):               0.00
Time:                        17:03:55   Log-Likelihood:                 476.23
No. Observations:                 941   AIC:                            -928.5
Df Residuals:                     929   BIC:                            -870.3
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                       -0.5300      0.161     -3.294      0.001      -0.846      -0.214
Data_Color[T.Bluish-Green]      -0.0289      0.025     -1.166      0.244      -0.077       0.020
Data_Color[T.Green]              0.0039      0.020      0.189      0.850      -0.036       0.044
Data_Color[T.Unknown]            0.0015      0.024      0.060      0.952      -0.046       0.049
Data_Type_Species[T.Robusta]    -0.0260      0.029     -0.890      0.374      -0.083       0.031
Data_Scores_Aroma                0.2014      0.022      9.133      0.000       0.158       0.245
Data_Scores_Aftertaste           0.5003      0.027     18.669      0.000       0.448       0.553
Data_Scores_Acidity              0.2479      0.024     10.501      0.000       0.202       0.294
Data_Scores_Body                 0.0420      0.022      1.877      0.061      -0.002       0.086
Data_Scores_Balance              0.0573      0.025      2.335      0.020       0.009       0.105
Data_Scores_Uniformity           0.0198      0.010      1.986      0.047       0.000       0.039
Data_Scores_Moisture             0.1476      0.116      1.270      0.205      -0.081       0.376
==============================================================================
Omnibus:                       46.261   Durbin-Watson:                   1.900
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              138.176
Skew:                          -0.139   Prob(JB):                     9.90e-31
Kurtosis:                       4.857   Cond. No.                         663.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [45]:
#One that predicts Flavor with all explanatory variables except for Moisture
lr_flavor_except_moisture = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Aroma+Data_Scores_Aftertaste+Data_Scores_Acidity+Data_Scores_Body+Data_Scores_Balance+Data_Scores_Uniformity+Data_Scores_Sweetness+Data_Color+Data_Type_Species",data=filtered_drop).fit()
lr_flavor_except_moisture.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.819
Model:                            OLS   Adj. R-squared:                  0.817
Method:                 Least Squares   F-statistic:                     383.4
Date:                Sat, 23 Sep 2023   Prob (F-statistic):               0.00
Time:                        17:04:16   Log-Likelihood:                 478.83
No. Observations:                 941   AIC:                            -933.7
Df Residuals:                     929   BIC:                            -875.5
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                       -0.6447      0.168     -3.837      0.000      -0.974      -0.315
Data_Color[T.Bluish-Green]      -0.0273      0.025     -1.106      0.269      -0.076       0.021
Data_Color[T.Green]              0.0042      0.020      0.206      0.836      -0.036       0.044
Data_Color[T.Unknown]           -0.0033      0.024     -0.135      0.893      -0.051       0.044
Data_Type_Species[T.Robusta]     0.0343      0.038      0.900      0.368      -0.040       0.109
Data_Scores_Aroma                0.2046      0.022      9.292      0.000       0.161       0.248
Data_Scores_Aftertaste           0.4946      0.027     18.566      0.000       0.442       0.547
Data_Scores_Acidity              0.2475      0.024     10.514      0.000       0.201       0.294
Data_Scores_Body                 0.0439      0.022      1.969      0.049       0.000       0.088
Data_Scores_Balance              0.0521      0.024      2.130      0.033       0.004       0.100
Data_Scores_Uniformity           0.0086      0.011      0.786      0.432      -0.013       0.030
Data_Scores_Sweetness            0.0287      0.011      2.599      0.010       0.007       0.050
==============================================================================
Omnibus:                       44.728   Durbin-Watson:                   1.902
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              132.187
Skew:                          -0.126   Prob(JB):                     1.98e-29
Kurtosis:                       4.819   Cond. No.                         773.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [46]:
#One that predicts Flavor with all explanatory variables except for Color
lr_flavor_except_color = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Aroma+Data_Scores_Aftertaste+Data_Scores_Acidity+Data_Scores_Body+Data_Scores_Balance+Data_Scores_Uniformity+Data_Scores_Sweetness+Data_Scores_Moisture+Data_Type_Species",data=filtered_drop).fit()
lr_flavor_except_color.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.819
Model:                            OLS   Adj. R-squared:                  0.817
Method:                 Least Squares   F-statistic:                     468.0
Date:                Sat, 23 Sep 2023   Prob (F-statistic):               0.00
Time:                        17:04:36   Log-Likelihood:                 477.54
No. Observations:                 941   AIC:                            -935.1
Df Residuals:                     931   BIC:                            -886.6
Df Model:                           9                                         
Covariance Type:            nonrobust                                         
================================================================================================
                                   coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------
Intercept                       -0.6473      0.167     -3.866      0.000      -0.976      -0.319
Data_Type_Species[T.Robusta]     0.0389      0.038      1.022      0.307      -0.036       0.114
Data_Scores_Aroma                0.2051      0.022      9.333      0.000       0.162       0.248
Data_Scores_Aftertaste           0.4931      0.027     18.495      0.000       0.441       0.545
Data_Scores_Acidity              0.2492      0.023     10.603      0.000       0.203       0.295
Data_Scores_Body                 0.0425      0.022      1.925      0.055      -0.001       0.086
Data_Scores_Balance              0.0515      0.024      2.104      0.036       0.003       0.099
Data_Scores_Uniformity           0.0088      0.011      0.799      0.425      -0.013       0.030
Data_Scores_Sweetness            0.0286      0.011      2.588      0.010       0.007       0.050
Data_Scores_Moisture             0.1253      0.111      1.129      0.259      -0.092       0.343
==============================================================================
Omnibus:                       45.580   Durbin-Watson:                   1.889
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              137.268
Skew:                          -0.123   Prob(JB):                     1.56e-30
Kurtosis:                       4.855   Cond. No.                         772.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [51]:
#One that predicts Flavor with all explanatory variables except for Species
lr_flavor_except_species = smf.ols(formula="Data_Scores_Flavor~Data_Scores_Aroma+Data_Scores_Aftertaste+Data_Scores_Acidity+Data_Scores_Body+Data_Scores_Balance+Data_Scores_Uniformity+Data_Scores_Sweetness+Data_Scores_Moisture+Data_Color",data=filtered_drop).fit()
lr_flavor_except_species.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:     Data_Scores_Flavor   R-squared:                       0.820
Model:                            OLS   Adj. R-squared:                  0.817
Method:                 Least Squares   F-statistic:                     383.5
Date:                Sat, 23 Sep 2023   Prob (F-statistic):               0.00
Time:                        17:09:32   Log-Likelihood:                 478.98
No. Observations:                 941   AIC:                            -934.0
Df Residuals:                     929   BIC:                            -875.8
Df Model:                          11                                         
Covariance Type:            nonrobust                                         
==============================================================================================
                                 coef    std err          t      P>|t|      [0.025      0.975]
----------------------------------------------------------------------------------------------
Intercept                     -0.6325      0.166     -3.812      0.000      -0.958      -0.307
Data_Color[T.Bluish-Green]    -0.0291      0.025     -1.179      0.239      -0.078       0.019
Data_Color[T.Green]            0.0028      0.020      0.138      0.890      -0.037       0.043
Data_Color[T.Unknown]         -0.0002      0.024     -0.008      0.994      -0.048       0.048
Data_Scores_Aroma              0.2042      0.022      9.273      0.000       0.161       0.247
Data_Scores_Aftertaste         0.4995      0.027     18.755      0.000       0.447       0.552
Data_Scores_Acidity            0.2475      0.024     10.516      0.000       0.201       0.294
Data_Scores_Body               0.0420      0.022      1.886      0.060      -0.002       0.086
Data_Scores_Balance            0.0534      0.024      2.182      0.029       0.005       0.102
Data_Scores_Uniformity         0.0110      0.011      1.047      0.295      -0.010       0.032
Data_Scores_Sweetness          0.0211      0.008      2.499      0.013       0.005       0.038
Data_Scores_Moisture           0.1231      0.116      1.060      0.289      -0.105       0.351
==============================================================================
Omnibus:                       44.373   Durbin-Watson:                   1.902
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              131.342
Skew:                          -0.120   Prob(JB):                     3.02e-29
Kurtosis:                       4.815   Cond. No.                         765.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [52]:
lr_flavor_except_species.rsquared

0.8195343578813457

### 4.2. Answer

Use your analyses from 4.1 to answer the research question.

Uniformity had the least amount of predictive power. We know this because when we took out uniformity the r-squared was the highest meaning that it has the lowest r^squared value, meaning it has the least amount of predictive power.